spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:${DATABASE_PORT:5433}/productdb
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update